# Codecov configuration
# Documentation: https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**"
  - "**/__init__.py"
  - "alembic/**"
  - "mycelery/**"
  - "app/main.py"  # Mostly boilerplate

flags:
  unittests:
    paths:
      - app/core/
      - app/schemas/
    carryforward: true

  integration:
    paths:
      - app/api/
      - app/models/
    carryforward: true

  e2e:
    paths:
      - app/
    carryforward: true

github_checks:
  annotations: true
